//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HaliSahaWPF.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sahalar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Sahalar()
        {
            this.OdemeIslemleris = new HashSet<OdemeIslemleri>();
            this.Rezervasyons = new HashSet<Rezervasyon>();
        }
    
        public int SahaId { get; set; }
        public string SahaAdı { get; set; }
        public Nullable<decimal> SahaFiyati { get; set; }
        public Nullable<int> SahaKapasitesi { get; set; }
        public Nullable<bool> isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OdemeIslemleri> OdemeIslemleris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rezervasyon> Rezervasyons { get; set; }
    }
}
